alias ls='ls --color="auto"'
alias ll='ls -alF --group-directories-first'
alias la='ls -a --group-directories-first'
alias l='ls -CF --group-directories-first'
alias vbash='vim ~/.bashrc'
alias vvim='vim ~/.vimrc'
alias balias='vim ~/.bash_aliases'
alias valias='vim $ZSH_CUSTOM/alias.zsh'
alias vzsh='vim ~/.zshrc'
alias v='vim'
alias python='python3'
alias pip='pip3'
alias c='clear'
alias home='cd ~'
alias src='source ~/.zshrc'
alias vtheme='vim ~/.config/zsh/themes/theme.zsh-theme'
